---
title: "May 2"
author: "Andrew Lai"
date: "30/04/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, message = FALSE}
source("April26_Ipums.R")
```

```{r}
rm(list=ls()[! ls() %in% c("rural_ipums","ruca", "subset_glass", 
                           "poverty_ipums", "pct_chg_aug", 
                           "industry_ipums", "aug_combined", 
                           "buffer1_vec","buffer2_perim_vec", 
                           "buffer2_vec", "cf_bf1", "cf_bf2", "gfperimvec",
                           "not_zcta", "rural_ruca", "zcta_cali", '%notin%')])
```

## pct change by zip code - zip code specific plots 

```{r}
pct_chg_aug %>%
  na.omit() %>%
  group_by(week,zcta,fire_cat) %>%
  summarize(med = median(pct_chg_mon_f), .groups = 'drop') %>%
  ggplot(data =., aes(x = week, y = med, group = zcta)) +
  scale_color_manual(values=c('Blue','Green', 'Red')) +
  geom_line(aes(colour=fire_cat), alpha = 0.2) +
  geom_point(aes(colour = fire_cat), alpha = 0.8) +
  ylim(-50,200) +
  scale_x_date(breaks = "1 week", limits = as.Date(c("2020-08-31", "2020-10-12"))) +# week of Oct 12
  theme(axis.text.x = element_text(angle = 0)) + 
  labs(x="Date", y="Median Percent Change") +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))  +
    annotate("rect", xmin = as.Date("2020-09-21"), xmax = as.Date("2020-10-12"), 
           ymin = -50.00, ymax = 150.00 ,
             alpha = 0, color= "orange")
```

```{r}
pct_chg_aug %>%
  na.omit() %>%
  group_by(week,zcta,fire_cat) %>%
  summarize(med = median(pct_chg_mon_z), .groups = 'drop') %>%
  ggplot(data =., aes(x = week, y = med, group = zcta)) +
  scale_color_manual(values=c('Blue','Green', 'Red')) +
  geom_line(aes(colour=fire_cat), alpha = 0.2) +
  geom_point(aes(colour = fire_cat), alpha = 0.8) +
  ylim(-50,200) +
  scale_x_date(breaks = "1 week", limits = as.Date(c("2020-08-31", "2020-10-12"))) +# week of Oct 12
  theme(axis.text.x = element_text(angle = 0)) + 
  labs(x="Date", y="Median Percent Change") +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))  +
    annotate("rect", xmin = as.Date("2020-09-21"), xmax = as.Date("2020-10-12"), 
           ymin = -50.00, ymax = 150.00 ,
             alpha = 0, color= "orange")
```


```{r}
pct_chg_aug %>%
  na.omit() %>%
  group_by(week,zcta,Agr_Dummy_75, fire_cat) %>%
  summarize(med = median(pct_chg_mon_f), .groups = 'drop') %>%
  ggplot(data =., aes(x = week, y = med, group = zcta)) +
  scale_color_manual(values=c('Blue','Green', 'Red')) +
  geom_line(aes(colour=Agr_Dummy_75), alpha = 0.2) +
  geom_point(aes(colour = Agr_Dummy_75), alpha = 0.8) +
  ylim(-50,200) +
  scale_x_date(breaks = "1 week", limits = as.Date(c("2020-08-31", "2020-10-12"))) +# week of Oct 12
  theme(axis.text.x = element_text(angle = 0)) + 
  labs(x="Date", y="Median Percent Change") + facet_wrap(vars(fire_cat), nrow = 3)
```

```{r}
pct_chg_aug %>%
  na.omit() %>%
  group_by(week,zcta,Poverty_Dummy_75, fire_cat) %>%
  summarize(med = median(pct_chg_mon_f), .groups = 'drop') %>%
  ggplot(data =., aes(x = week, y = med, group = zcta)) +
  scale_color_manual(values=c('Blue','Green', 'Red')) +
  geom_line(aes(colour=Poverty_Dummy_75), alpha = 0.2) +
  geom_point(aes(colour = Poverty_Dummy_75), alpha = 0.8) +
  ylim(-50,200) +
  scale_x_date(breaks = "1 week", limits = as.Date(c("2020-08-31", "2020-10-12"))) +# week of Oct 12
  theme(axis.text.x = element_text(angle = 0)) + 
  labs(x="Date", y="Median Percent Change") + facet_wrap(vars(fire_cat), nrow = 3)
```



```{r}
pct_chg_aug %>%
  group_by(zcta, Agr_Dummy_75, fire_cat) %>%
  distinct(zcta, fire_cat) %>%
  group_by(Agr_Dummy_75, fire_cat) %>%
  summarize(n = n())
```


```{r}
pct_chg_aug %>%
  group_by(zcta, Rural_Dummy_R, fire_cat) %>%
  distinct(zcta, fire_cat) %>%
  group_by(Rural_Dummy_R, fire_cat) %>%
  summarize(n = n())
```

```{r}
pct_chg_aug %>%
  group_by(zcta, Poverty_Dummy_75, fire_cat) %>%
  distinct(zcta, fire_cat) %>%
  group_by(Poverty_Dummy_75, fire_cat) %>%
  summarize(n = n())
```


```{r}
pct_chg_aug %>%
  group_by(zcta, Agr_Dummy_75, fire_cat) %>%
  distinct(zcta, fire_cat) %>%
  group_by(zcta, Agr_Dummy_75) %>%
  summarize(n = n())
```


```{r}
aug_combined %>%
  filter(zcta %in% zcta_cali) %>%
  distinct(po_name, zcta) %>%
  select(po_name, zcta) %>%
  arrange(po_name)
```



```{r}
pct_chg_aug %>%
  na.omit() %>%
  group_by(week,zcta) %>%
  group_by(Agr_Dummy_75, week, fire_cat) %>%
  filter(fire_cat == 'GF') %>%
  summarize(med = median(pct_chg_mon_f), .groups ='drop') %>%
  ggplot(data =., aes(x = week, y = med, group = Agr_Dummy_75)) +
  scale_color_manual(values=c('Blue','Green', 'Red')) +
  geom_line(aes(colour=Agr_Dummy_75)) +
  geom_point(size = 2) +
  scale_x_date(breaks = "1 week", limits = as.Date(c("2020-08-31", "2020-10-12"))) +# week of Oct 12
  theme(axis.text.x = element_text(angle = 0)) + 
  labs(x="Date", y="Median Percent Change") +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))  +
    annotate("rect", xmin = as.Date("2020-09-21"), xmax = as.Date("2020-10-12"), 
           ymin = -20, ymax = 60 ,
             alpha = 0, color= "orange")
  ggtitle("Median Raw Visits by Date") 
```

```{r}
# Agriculture BY Fire Cat
pct_chg_aug %>%
  na.omit() %>%
  group_by(week,zcta, fire_cat) %>%
  group_by(Agr_Dummy_75, week, fire_cat) %>%
  summarize(med = median(pct_chg_mon_f), .groups ='drop') %>%
  ggplot(data =., aes(x = week, y = med, group = Agr_Dummy_75)) +
  scale_color_manual(values=c('Blue','Green', 'Red')) +
  geom_line(aes(colour=Agr_Dummy_75)) +
  geom_point(size = 2) +
  scale_x_date(breaks = "1 week", limits = as.Date(c("2020-08-31", "2020-10-12")))  +# week of Oct 12

  theme(axis.text.x = element_text(angle = 0)) + facet_wrap(vars(fire_cat), nrow = 3) +ylim(-50,50)
```



```{r}
pct_chg_aug %>%
  na.omit() %>%
  group_by(week,zcta) %>%
  group_by(Poverty_Dummy_75, week, fire_cat) %>%
  filter(fire_cat == 'GF') %>%
  summarize(med = median(pct_chg_mon_f), .groups ='drop') %>%
  ggplot(data =., aes(x = week, y = med, group = Poverty_Dummy_75)) +
  scale_color_manual(values=c('Blue','Green', 'Red')) +
  geom_line(aes(colour=Poverty_Dummy_75)) +
  geom_point(size = 2) +
  scale_x_date(breaks = "1 week", limits = as.Date(c("2020-08-31", "2020-10-12"))) +# week of Oct 12
  theme(axis.text.x = element_text(angle = 0)) + 
  labs(x="Date", y="Median Percent Change") +
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black"))  +
    annotate("rect", xmin = as.Date("2020-09-21"), xmax = as.Date("2020-10-12"), 
           ymin = -25, ymax = 60 ,
             alpha = 0, color= "orange")
  ggtitle("Median Raw Visits by Date")
```

```{r}
# Poverty BY Fire Cat
pct_chg_aug %>%
  na.omit() %>%
  group_by(week,zcta, fire_cat) %>%
  group_by(Poverty_Dummy_75, week, fire_cat) %>%
  summarize(med = median(pct_chg_mon_f), .groups ='drop') %>%
  ggplot(data =., aes(x = week, y = med, group = Poverty_Dummy_75)) +
  scale_color_manual(values=c('Blue','Green', 'Red')) +
  geom_line(aes(colour=Poverty_Dummy_75)) +
  geom_point(size = 2) +
  scale_x_date(breaks = "1 week", limits = as.Date(c("2020-08-31", "2020-10-12")))  +# week of Oct 12

  theme(axis.text.x = element_text(angle = 0)) + facet_wrap(vars(fire_cat), nrow = 3) + ylim(-75,100)
```



## regressions

```{r}
summary(lm(pct_chg_mon_f~ as.factor(week) + Poverty_Dummy_50, data=subset(pct_chg_aug, fire_cat=="GF")))
```


```{r}
summary(lm(pct_chg_mon_f ~ fire_cat + Rural_Dummy_R +  week*fire_cat, data = pct_chg_aug))
```





##  read up on arima or other time series regression and forecasting to work on


## FD Model

```{r}
library(quantreg)
```


```{r}
r1 <- rq(formula = pct_chg_mon_f ~ Pct_Agg_P + Rural_Dummy_R, tau = 0.75, 
   data=subset(pct_chg_aug, fire_cat=="GF"))

summary(r1)
```

-- data 2018 - 2020 
-- look into time series model

-- aggregate counts of visits within each zip code (seperated by week)
-- clean up r script + markdown + push to github
